# Generated by Django 5.2.4 on 2025-08-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vegetablerate_delete_marketprice_alter_crop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablerate',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
